### ISSUE TITLE
Bluetooth headset unable to pause/stop music playback

### ISSUE THREAD

**Issue by rhithyn** [vanilla-music/vanilla-music.github.io#1]
I have a Cardo SmartPack Bluetooth headset/intercom system for my helmet paired with my Galaxy Note 8.

When the headset is connected to my phone I can start music by pressing the action button, short tap to skip forward and I can also skip back a track by double tapping this button.  On other players (Google Music Player, Samsung Music Player, AIMP, Odyssey), press and hold will send a stop or pause and consequently stop music playback.

Vanilla music player ignores it.

Unfortunately, the inane design for this headset requires music to stop playing to be able to use other modes, like FM or to even just turn it off, but I can't get Vanilla to stop playing.

Any ideas on what I could do to figure this one out?

**Comment by rhithyn** [comment]
So, no comments or suggestions, just close it?  Thanks.

**Comment by adrian-bl** [comment]
Sorry: i just closed it because it was unnoticed for 2 months as this is the wrong issue tracker.

Feel free to open a new bug at https://github.com/vanilla-music/vanilla/issues - also: a logcat will most likely help to debug the issue.

**Comment by rhithyn** [comment]
My apologies.  I wasn't aware this was a defunct bug database.  Thanks for the links.
